repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: flake8
        args: ['--max-line-length=120']
-   repo: https://github.com/pre-commit/pre-commit
    sha: v1.6.0
    hooks:
    -   id: validate_manifest
-   repo: https://github.com/asottile/reorder_python_imports
    sha: v1.0.1
    hooks:
    -   id: reorder-python-imports
        language_version: python2.7
-   repo: https://github.com/asottile/pyupgrade
    sha: v1.2.0
    hooks:
    -   id: pyupgrade
#-   repo: https://github.com/vikramarsid/code_fixers.git
#    sha: 0306531133cf9a5b48535f6e955d8929753f7f6d
#    hooks:
#    -   id: error_number_fixer
#        language_version: python2.7
