-   id: error_number_fixer
    name: error number fixer
    description: "Fixes error numbers in the error logs"
    entry: error_number_fixer
    language: python
    types: [python]
    args: [-i]
    files: (^|/)src/.+\.py$
    minimum_pre_commit_version: 0.15.0
